### ISSUE TITLE
Use branching for development

### ISSUE THREAD

**Issue by avats-dev** [A-Team-IIITDMJ/a-team-iiitdmj.github.io#6]
Create branches from `master` for any edits or updates and once you're sure it's working then open a PR.
This would
- help in maintaining changes in long run
- allow others to review and update with new tweaks
- help in avoiding build for stable release through master.

A good approach would be to create a `develop` branch first, and then push your changes to it, and when it's running all good, merge that with `master` for stable release.

> **Just a suggestion for better development.** Feel free to close this issue. :+1:

**Comment by abhishek-geek** [comment]
Yes, that was a wonderful suggestion. Started editing in different branches from this morning.

**Comment by avats-dev** [comment]
Nice work :rocket: Also, I'm closing this one. 
> Open a new issue if you're stuck or need help and tag me :smile:
